# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'AssignmentCompany_New' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SearchTextField'

  target 'AssignmentCompany_NewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentCompany_NewUITests' do
    # Pods for testing
  end

end
